package com.client.client.DTO.enumeration;

public enum TypeError {
    APPOINTMENT_MONTH_NOT_VALID, APPOINTMENT_YEAR_NOT_VALID, APPOINTMENT_DAY_NOT_VALID, APPOINTMENT_HOUR_NOT_VALID,
    BANK_ACCOUNT_NOT_VALID, BANK_SECURITY_NUMBER_NOT_VALID,
    USER_PASSWORD_NOT_VALID, USER_PHONE_NUMBER_NOT_VALID,USER_USERNAME_DUPLAICATE,
    DRUG_QUANTITY_NOT_VALID, DRUG_PRICE_NOT_VALID,
}
